export {
  createOfficeEditor,
  mountOfficeEditor,
  getActiveOfficeEditorCount,
  loadOfficeEditorApi,
  type CreateOfficeEditorOptions,
  type OfficeEditorInput,
  type OfficeEditorInstance,
  type OfficeEditorMount,
  type OfficeEditorMountPhase,
  type OfficeEditorMountState,
  type OfficeInterfaceTheme,
  type OfficePluginOptions,
  type OfficeDownloadCallbackResult,
  type OfficeEditorMode,
  type OfficeEditorSourceKind,
  type OfficeEditorState,
  OfficeEditorStartupError,
  type OfficeHostUrlContext,
  type OfficeHostUrlResolver,
  type OfficeHostIdentity,
  OfficeHostIdentityMismatchError,
  OfficeHostIsolationError,
  type OfficeSaveBehavior,
  type OfficeSaveAsCallbackResult,
  type OfficeSaveCallbackResult,
  type OfficeSaveToNewFormatConfirmationOptions,
} from './lib/office-editor';
